import type { Metadata } from "next";
import Head from "next/head"; // Import Head component from Next.js

import "./global.scss";

export const metadata: Metadata = {
  title: "Test task for ABZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
        <link rel='preload' href='/public/img/main-bg-img.webp' as='image' />
        <link
          rel='preload'
          href='/public/img/main-bg-img-mobile.webp'
          as='image'
        />
      </Head>
      <body>{children}</body>
    </html>
  );
}
