import type { Metadata } from "next";

import "./global.scss";

export const metadata: Metadata = {
  title: "Test task for ABZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
